# List of servers to use
server_names = ['cloudflare-family']

# List of local addresses and ports to listen to
listen_addresses = []

# Maximum number of simultaneous client connections to accept
max_clients = 250

# How long a DNS query will wait for a response, in milliseconds
timeout = 5000

# Keepalive for HTTP (HTTPS, HTTP/2) queries, in seconds
keepalive = 30

# Delay, in minutes, after which certificates are reloaded
cert_refresh_delay = 240

# Enable a DNS cache to reduce latency and outgoing traffic
cache = true

# Cache size
cache_size = 4096

# Minimum TTL for cached entries
cache_min_ttl = 2400

# Maximum TTL for cached entries
cache_max_ttl = 86400

# Minimum TTL for negatively cached entries
cache_neg_min_ttl = 60

# Maximum TTL for negatively cached entries
cache_neg_max_ttl = 600

# Log client queries to a file
[query_log]
  file = '/var/log/dnscrypt-proxy/query.log'
  format = 'tsv'

# Log queries for nonexistent zones
[nx_log]
  file = '/var/log/dnscrypt-proxy/nx.log'
  format = 'tsv'

# Remote lists of available servers
[sources]
  [sources.'public-resolvers']
    urls = [
      'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md',
      'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md',
      'https://ipv6.download.dnscrypt.info/resolvers-list/v3/public-resolvers.md',
      'https://download.dnscrypt.net/resolvers-list/v3/public-resolvers.md'
    ]
    cache_file = '/var/lib/dnscrypt-proxy/public-resolvers.md'
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    refresh_delay = 72
    prefix = ''
